// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBwXWsvTBGZoMzHXUQ8H7fuX1iXgoKYdE',
    appId: '1:110027941500:web:c7b06d537ed99e20114bf9',
    messagingSenderId: '110027941500',
    projectId: 'floengtech',
    authDomain: 'floengtech.firebaseapp.com',
    storageBucket: 'floengtech.appspot.com',
    measurementId: 'G-7RSC3LG1FS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVKDc1Z7XPslS96VZkHNPEIhwxPvFJNAc',
    appId: '1:110027941500:android:04294822bd2ca965114bf9',
    messagingSenderId: '110027941500',
    projectId: 'floengtech',
    storageBucket: 'floengtech.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzEbBqZY2BuIyQFaKV2CJLNlJSB6QG2MI',
    appId: '1:110027941500:ios:8a388f70c92afb31114bf9',
    messagingSenderId: '110027941500',
    projectId: 'floengtech',
    storageBucket: 'floengtech.appspot.com',
    iosBundleId: 'com.example.appta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzEbBqZY2BuIyQFaKV2CJLNlJSB6QG2MI',
    appId: '1:110027941500:ios:8a388f70c92afb31114bf9',
    messagingSenderId: '110027941500',
    projectId: 'floengtech',
    storageBucket: 'floengtech.appspot.com',
    iosBundleId: 'com.example.appta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBwXWsvTBGZoMzHXUQ8H7fuX1iXgoKYdE',
    appId: '1:110027941500:web:9bf680d1e87cda2b114bf9',
    messagingSenderId: '110027941500',
    projectId: 'floengtech',
    authDomain: 'floengtech.firebaseapp.com',
    storageBucket: 'floengtech.appspot.com',
    measurementId: 'G-F9ZFWWSM1P',
  );
}
